version: '3'

services:
  musixmatchbot:
    image: starboy369/musixmatchbot
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    restart: always
    env_file:
      - ./.env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
