              #  environment:
              #      BOT_TOKEN: "1919983785:AAESmFoHDl8taD7TgIwlvNWzQCuoRMlwSnA"
              #      MUSIXMATCH_API_KEY: "fe689d8c63412e0916fc373de96e1b6e"
version: '3'

services:
  musixmatchbot:
    image: musixmatchbot/musixmatchbot
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"
    restart: always
    env_file:
          - ./.env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --scope myscope
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.scope=myscope"