name: PyLint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint
      run: |
        pylint . --rcfile=.pylintrc
    - name: update Docker image
      if: ${{ github.event_name == 'push' || github.event.pull_request.merge }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
# sudo docker-compose up -d
        sudo docker build --tag musixmatchbot/musixmatchbot .
        sudo docker push musixmatchbot/musixmatchbot
